#define PIN_BUTTON_START_60 5
#define PIN_BUTTON_START_20 6
#define PIN_BUTTON_RESET 7
#define PIN_BUTTON_TABLE_1 0
#define PIN_BUTTON_TABLE_2 1

#define BUTTON_PRESSED 0

#define STATE_INIT 0
#define STATE_WAITING 1
#define STATE_STARTED 2
#define STATE_STOPPED 3

#define TABLE_1 1
#define TABLE_2 2
#define NO_TABLE 0

