#define MAX_TABLES 4

#define PIN_BUTTON_START_60 5
#define PIN_BUTTON_START_20 6
#define PIN_BUTTON_RESET 7
#define PIN_BUTTON_TABLE_0 0
#define PIN_BUTTON_TABLE_1 1
#define PIN_BUTTON_TABLE_2 2
#define PIN_BUTTON_TABLE_3 3

#define PIN_BUZZER 8
#define PIN_LED_START 13
#define PIN_LED_TABLE_3 12
#define PIN_LED_TABLE_2 11
#define PIN_LED_TABLE_1 10
#define PIN_LED_TABLE_0 9

#define BUTTON_PRESSED 0

#define STATE_INIT 0
#define STATE_WAITING 1
#define STATE_STARTED 2
#define STATE_STOPPED 3

#define TABLE_COLLISION -2
#define NO_TABLE -1
#define TABLE_0 0
#define TABLE_1 1
#define TABLE_2 2
#define TABLE_3 3

//#define START_SCREEN_TIME 1.00

#define ERROR_NOT_INITED 0
#define ERROR_UNKNOWN_STATE 1
#define ERROR_BUTTONS_COLLISION 2
